name: Swimi
options:
  bundleIdPrefix: com.kainosk
targets:
  Swimi:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Swimi]
    scheme:
      testTargets:
        - SwimiTests
      gatherCoverageData: true
  SwimiTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.0"
    sources: [SwimiTests]
    dependencies:
      - target: Swimi
      - carthage: Quick
      - carthage: Nimble
